version: "3"

services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - 5000:5000
    command: yarn dev
    restart: always
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/smite
    volumes:
      - ./:/app/

  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    ports:
      - 3306:3306
    expose:
      - 3306
    restart: always
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - smite-db:/var/lib/mysql

volumes:
  smite-db:
